# Generated by Django 4.2.16 on 2025-09-10 13:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(blank=True, max_length=200)),
                ('dosage_form', models.CharField(max_length=50)),
                ('strength', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=200)),
                ('side_effects', models.TextField(blank=True)),
                ('contraindications', models.TextField(blank=True)),
                ('is_prescription_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'medicines',
                'indexes': [models.Index(fields=['name'], name='medicines_name_017048_idx'), models.Index(fields=['generic_name'], name='medicines_generic_850df6_idx'), models.Index(fields=['is_active'], name='medicines_is_acti_508f30_idx')],
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('INFECTIOUS', 'Infectious'), ('CHRONIC', 'Chronic'), ('ACUTE', 'Acute'), ('GENETIC', 'Genetic'), ('MENTAL', 'Mental Health'), ('CARDIOVASCULAR', 'Cardiovascular'), ('RESPIRATORY', 'Respiratory'), ('NEUROLOGICAL', 'Neurological'), ('CANCER', 'Cancer'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('symptoms', models.TextField(blank=True)),
                ('icd_code', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'diseases',
                'indexes': [models.Index(fields=['name'], name='diseases_name_82f10d_idx'), models.Index(fields=['category'], name='diseases_categor_1a7715_idx'), models.Index(fields=['icd_code'], name='diseases_icd_cod_9c2ee6_idx'), models.Index(fields=['is_active'], name='diseases_is_acti_a996a2_idx')],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BAGHDAD', 'بغداد'), ('BASRA', 'البصرة'), ('MOSUL', 'الموصل'), ('ERBIL', 'أربيل'), ('NAJAF', 'النجف'), ('KARBALA', 'كربلاء'), ('KIRKUK', 'كركوك'), ('NAJAF', 'النجف'), ('SULAYMANIYAH', 'السليمانية'), ('WASIT', 'واسط'), ('BABIL', 'بابل'), ('QADISIYAH', 'القادسية'), ('MAYSAN', 'ميسان'), ('DIWANIYAH', 'الديوانية'), ('MUTHANNA', 'المثنى'), ('THI_QAR', 'ذي قار'), ('ANBAR', 'الأنبار'), ('SALAH_AL_DIN', 'صلاح الدين'), ('DIYALA', 'ديالى'), ('DUHOK', 'دهوك')], max_length=100, unique=True, verbose_name='اسم المدينة')),
                ('state', models.CharField(max_length=100, verbose_name='المحافظة')),
                ('country', models.CharField(default='Iraq', max_length=100, verbose_name='البلد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مدينة',
                'verbose_name_plural': 'المدن',
                'db_table': 'cities',
                'indexes': [models.Index(fields=['name'], name='cities_name_a7bf2e_idx'), models.Index(fields=['state'], name='cities_state_fd8d03_idx')],
            },
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المركز')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centers', to='hospital.city', verbose_name='المدينة')),
            ],
            options={
                'verbose_name': 'مركز طبي',
                'verbose_name_plural': 'المراكز الطبية',
                'db_table': 'centers',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('ADMINISTRATION', 'Administration'), ('NURSING', 'Nursing'), ('LABORATORY', 'Laboratory'), ('PHARMACY', 'Pharmacy'), ('RADIOLOGY', 'Radiology'), ('RECEPTION', 'Reception'), ('HOUSEKEEPING', 'Housekeeping'), ('SECURITY', 'Security')], max_length=20)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='hospital.center')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staff',
                'indexes': [models.Index(fields=['center'], name='staff_center__6c5ddb_idx'), models.Index(fields=['department'], name='staff_departm_db298c_idx'), models.Index(fields=['is_active'], name='staff_is_acti_e9a75c_idx'), models.Index(fields=['employee_id'], name='staff_employe_f9cdad_idx')],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('CARDIOLOGY', 'أمراض القلب'), ('NEUROLOGY', 'أمراض الأعصاب'), ('ONCOLOGY', 'الأورام'), ('PEDIATRICS', 'طب الأطفال'), ('GYNECOLOGY', 'أمراض النساء والولادة'), ('ORTHOPEDICS', 'العظام'), ('DERMATOLOGY', 'الأمراض الجلدية'), ('PSYCHIATRY', 'الطب النفسي'), ('RADIOLOGY', 'الأشعة'), ('ANESTHESIOLOGY', 'التخدير'), ('EMERGENCY', 'الطوارئ'), ('GENERAL', 'الطب العام')], max_length=20, verbose_name='التخصص')),
                ('license_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='رقم الترخيص')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='سنوات الخبرة')),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='رسوم الاستشارة')),
                ('is_available', models.BooleanField(default=True, verbose_name='متاح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='hospital.center', verbose_name='المركز')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'طبيب',
                'verbose_name_plural': 'الأطباء',
                'db_table': 'doctors',
                'indexes': [models.Index(fields=['center'], name='doctors_center__407c43_idx'), models.Index(fields=['specialization'], name='doctors_special_6661e0_idx'), models.Index(fields=['is_available'], name='doctors_is_avai_62f7a8_idx'), models.Index(fields=['license_number'], name='doctors_license_1ed880_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='center',
            index=models.Index(fields=['city'], name='centers_city_id_49eb5e_idx'),
        ),
        migrations.AddIndex(
            model_name='center',
            index=models.Index(fields=['is_active'], name='centers_is_acti_4a0b07_idx'),
        ),
        migrations.AddIndex(
            model_name='center',
            index=models.Index(fields=['name'], name='centers_name_1d0813_idx'),
        ),
    ]
