name: hospital-system
services:
- name: django-hospital-system2
  source_dir: /
  github:
    repo: ahmedwmh/Django_Hospital_System
    branch: main
  run_command: gunicorn hospital_system.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --access-logfile - --error-logfile -
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8000
  health_check:
    http_path: /
    initial_delay_seconds: 30
    period_seconds: 30
    timeout_seconds: 10
    success_threshold: 1
    failure_threshold: 3
  envs:
  - key: DEBUG
    value: "False"
  - key: SECRET_KEY
    value: "g)t28v^-shs^idfcd5830yb92f)o%rgvooi78a72nvp+e9jow7"
  - key: ALLOWED_HOSTS
    value: "hospital-system-u3uy4.ondigitalocean.app,localhost,127.0.0.1,*.ondigitalocean.app"
  - key: USE_POSTGRESQL
    value: "False"
  - key: STATIC_ROOT
    value: "/app/staticfiles"
  - key: MEDIA_ROOT
    value: "/app/media"
  - key: LANGUAGE_CODE
    value: "ar"
  - key: TIME_ZONE
    value: "Asia/Baghdad"
  - key: EMAIL_BACKEND
    value: "django.core.mail.backends.console.EmailBackend"
  - key: REDIS_URL
    value: ""
  routes:
  - path: /