name: django-hospital-system
services:
- name: web
  source_dir: /
  github:
    repo: ahmedwmh/djangoHospital
    branch: main
  build_command: pip install -r requirements.txt && python manage.py migrate --noinput && python manage.py collectstatic --noinput
  run_command: gunicorn hospital_system.wsgi:application --bind 0.0.0.0:8000 --workers 1 --timeout 120 --access-logfile - --error-logfile -
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8000
  routes:
  - path: /
  envs:
  - key: DEBUG
    value: "True"
  - key: SECRET_KEY
    value: "django-insecure-change-this-in-production-$(openssl rand -hex 32)"
  - key: ALLOWED_HOSTS
    value: "urchin-app-j2low.ondigitalocean.app,localhost,127.0.0.1,*.ondigitalocean.app"
  - key: USE_POSTGRESQL
    value: "False"
  - key: REDIS_URL
    value: ""
  - key: STATIC_ROOT
    value: "/app/staticfiles"
  - key: MEDIA_ROOT
    value: "/app/media"

databases:
- name: hospital-db
  engine: PG
  version: "15"
  size: db-s-1vcpu-1gb
  num_nodes: 1
