# Generated by Django 4.2.16 on 2025-09-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_name',
            field=models.CharField(default='', help_text='الاسم الكامل للمريض', max_length=200, verbose_name='اسم المريض'),
        ),
    ]
