# Generated by Django 4.2.16 on 2025-09-11 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
        ('patients', '0003_remove_other_gender_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_type', models.CharField(choices=[('CONSULTATION', 'استشارة'), ('FOLLOW_UP', 'متابعة'), ('EMERGENCY', 'طوارئ'), ('ROUTINE', 'روتيني'), ('VACCINATION', 'تطعيم'), ('OTHER', 'أخرى')], default='CONSULTATION', max_length=20, verbose_name='نوع الزيارة')),
                ('visit_date', models.DateTimeField(verbose_name='تاريخ ووقت الزيارة')),
                ('status', models.CharField(choices=[('SCHEDULED', 'مجدولة'), ('IN_PROGRESS', 'قيد التنفيذ'), ('COMPLETED', 'مكتملة'), ('CANCELLED', 'ملغية'), ('NO_SHOW', 'لم يحضر')], default='SCHEDULED', max_length=20, verbose_name='حالة الزيارة')),
                ('chief_complaint', models.TextField(help_text='وصف المشكلة أو السبب في الزيارة', verbose_name='الشكوى الرئيسية')),
                ('diagnosis', models.TextField(blank=True, help_text='التشخيص الطبي', verbose_name='التشخيص')),
                ('treatment_plan', models.TextField(blank=True, help_text='العلاج الموصى به', verbose_name='خطة العلاج')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات إضافية')),
                ('follow_up_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المتابعة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='hospital.doctor', verbose_name='الطبيب')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient', verbose_name='المريض')),
            ],
            options={
                'verbose_name': 'زيارة',
                'verbose_name_plural': 'الزيارات',
                'ordering': ['-visit_date'],
                'indexes': [models.Index(fields=['patient'], name='patients_vi_patient_093dfc_idx'), models.Index(fields=['doctor'], name='patients_vi_doctor__ed4026_idx'), models.Index(fields=['visit_date'], name='patients_vi_visit_d_2e4473_idx'), models.Index(fields=['status'], name='patients_vi_status_aacc0e_idx'), models.Index(fields=['visit_type'], name='patients_vi_visit_t_d647ed_idx')],
            },
        ),
    ]
