# Generated by Django 4.2.16 on 2025-09-10 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم التقرير')),
                ('report_type', models.CharField(choices=[('PATIENT_RECORD', 'سجل المريض'), ('TEST_RESULTS', 'نتائج الفحوصات'), ('TREATMENT_SUMMARY', 'ملخص العلاج'), ('SURGERY_REPORT', 'تقرير الجراحة'), ('PATIENTS_PER_CITY', 'المرضى حسب المدينة'), ('COMMON_DISEASES', 'الأمراض الشائعة'), ('CENTER_STATISTICS', 'إحصائيات المركز')], max_length=20, verbose_name='نوع التقرير')),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV')], max_length=10, verbose_name='الصيغة')),
                ('status', models.CharField(choices=[('PENDING', 'في الانتظار'), ('GENERATING', 'قيد التوليد'), ('COMPLETED', 'مكتمل'), ('FAILED', 'فشل')], default='PENDING', max_length=20, verbose_name='الحالة')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='مسار الملف')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='المعاملات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL, verbose_name='تم توليده بواسطة')),
            ],
            options={
                'verbose_name': 'تقرير',
                'verbose_name_plural': 'التقارير',
                'db_table': 'reports',
                'indexes': [models.Index(fields=['report_type'], name='reports_report__ff8b25_idx'), models.Index(fields=['status'], name='reports_status_e83c1d_idx'), models.Index(fields=['generated_by'], name='reports_generat_4a23eb_idx'), models.Index(fields=['created_at'], name='reports_created_c5f642_idx')],
            },
        ),
    ]
